### ISSUE TITLE
render get repeat result 

### ISSUE THREAD

**Issue by cocktail18** [FurqanSoftware/goldmark-katex#1]
#### code:
```
err := katex.Render(w, []byte("\\frac{1}{2} \\times 4 \\div 3"), true)
```

#### result:
![image](https://user-images.githubusercontent.com/45166983/231693277-ff223341-e0f6-44ed-8e29-85a2533f378e.png)

**Comment by hjr265** [comment]
@cocktail18 Did you include the Katex CSS?

https://katex.org/docs/browser.html
